version: "3.5"
services:
  mlflow-client-test-unit:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-unit}
    build:
      context: .
      dockerfile: Dockerfile.unit
    volumes:
      - ./mlflow_client:/app/mlflow_client
      - ./tests/unit:/app/tests/unit:ro
      - ./pytest_runner.sh:/app/pytest_runner.sh
      - ./unit-tests.sh:/app/unit-tests.sh
      - ./docs:/app/docs
      - ./setup.py:/app/setup.py
      - ./setup.cfg:/app/setup.cfg
      - ./README.rst:/app/README.rst
      - ./CHANGELOG.rst:/app/CHANGELOG.rst
      - ./MANIFEST.in:/app/MANIFEST.in
    network_mode: host