version: "3.5"
services:
  mlflow-client-test-unit:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-unit}
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    build:
      context: .
      dockerfile: Dockerfile.integration
    volumes:
      - ./mlflow_client:/app/mlflow_client:ro
      - ./tests/unit:/app/tests/unit:ro
      - ./unit-tests.sh:/app/unit-tests.sh:ro
    network_mode: host
