version: "3.5"
services:
  mlflow-client-test:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test}
    env_file: .env.test
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # for running local test, can be removed
      - ./tests:/app/tests:ro
    depends_on:
        - "mlflow-test"
    networks:
      - default
      - mlflow
  mlflow-test:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow:${MLFLOW_TAG:-latest}
    env_file: .env.test
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    restart: unless-stopped
    depends_on:
        - "mlflow-test-db"
    networks:
      - db
      - mlflow
  mlflow-test-db:
    image: postgres:11.8
    env_file: .env.test
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    restart: unless-stopped
    networks:
      - db
networks:
  mlflow:
    internal: true
  db:
    internal: true
