version: "3.5"
services:
  mlflow-client-test:
    image: docker.rep.msk.mts.ru/mlflow-client:${TAG:-test}
    env_file: .env.test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # for running local test, can be removed
      - ./tests:/app/tests:ro
    depends_on:
        - "mlflow-test"
    networks:
      - default
      - mlflow
    extra_hosts:
      - rep.msk.mts.ru:10.73.8.86
  mlflow-test:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow:${MLFLOW_TAG:-latest}
    env_file: .env.test
    restart: unless-stopped
    depends_on:
        - "mlflow-test-db"
    networks:
      - db
      - mlflow
  mlflow-test-db:
    image: postgres:11.8
    env_file: .env.test
    restart: unless-stopped
    environment:
      - PGDATABASE=$POSTGRES_DB
      - PGUSER=$POSTGRES_USER
      - PGPASSWORD=$POSTGRES_PASSWORD
    networks:
      - db
networks:
  mlflow:
    internal: true
  db:
    internal: true
