version: "3.5"
services:
  mlflow-client-jenkins-unit:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-integration}
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    build:
      context: .
      dockerfile: Dockerfile.unit
    volumes:
      - ./reports:/app/reports:rw
      - ./.coveragerc:/app/.coveragerc:ro
    network_mode: host
