version: '3.5'
services:
  mlflow-client-test-unit:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-unit}
    build:
      context: .
      dockerfile: Dockerfile.unit
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./mlflow_client:/app/mlflow_client
    - ./.git:/app/.git
    - ./.gitignore:/app/.gitignore
    - ./tests/unit:/app/tests/unit:ro
    - ./.coveragerc:/app/.coveragerc
    - ./pytest_runner.sh:/app/pytest_runner.sh
    - ./coverage.sh:/app/coverage.sh
    - ./unit-tests.sh:/app/unit-tests.sh
    - ./reports:/app/reports
    - ./.pre-commit-config.yaml:/app/.pre-commit-config.yaml
    - ./.pylintrc:/app/.pylintrc
    - ./pyproject.toml:/app/pyproject.toml
    - ./docs:/app/docs
    - ./setup.py:/app/setup.py
    - ./setup.cfg:/app/setup.cfg
    - ./README.rst:/app/README.rst
    - ./CHANGELOG.rst:/app/CHANGELOG.rst
    - ./MANIFEST.in:/app/MANIFEST.in
    network_mode: host
