version: '3.5'
services:
  mlflow-client-jenkins-integration:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test}
    env_file: .env.jenkins.integration
    build:
      context: .
      dockerfile: Dockerfile.integration
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./reports:/app/reports:rw
    - ./.coveragerc:/app/.coveragerc:ro
    depends_on:
    - mlflow-jenkins
    networks:
    - default
    - mlflow
  mlflow-jenkins:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow:${MLFLOW_TAG:-latest}
    env_file: .env.jenkins.integration
    restart: unless-stopped
    depends_on:
    - mlflow-jenkins-db
    networks:
    - db
    - mlflow
  mlflow-jenkins-db:
    image: postgres:11.8
    env_file: .env.jenkins.integration
    restart: unless-stopped
    networks:
    - db
networks:
  mlflow:
    internal: true
  db:
    internal: true
