version: "3.5"
services:
  mlflow-client-test-unit:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-unit}
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    build:
      context: .
      dockerfile: Dockerfile.unit
    volumes:
      - ./mlflow_client:/app/mlflow_client
      - ./tests/unit:/app/tests/unit:ro
      - ./pytest.ini:/app/pytest.ini
      - ./pytest_runner.sh:/app/pytest_runner.sh
      - ./unit-tests.sh:/app/unit-tests.sh
      - ./docs:/app/docs
      - ./setup.py:/app/setup.py
      - ./setup.cfg:/app/setup.cfg
      - ./README.rst:/app/README.rst
      - ./CHANGELOG.rst:/app/CHANGELOG.rst
      - ./MANIFEST.in:/app/MANIFEST.in
    extra_hosts:
      - rep.msk.mts.ru:10.73.8.86
      - repo.msk.mts.ru:10.73.8.86
