version: "3.5"
services:
  mlflow-client-test-integration:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow-client:${TAG:-test-integration}
    env_file: .env.test.integration
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    build:
      context: .
      dockerfile: Dockerfile.integration
    volumes:
      - ./mlflow_client:/app/mlflow_client
      - ./tests/integration:/app/tests/integration
      - ./pytest_runner.sh:/app/pytest_runner.sh
      - ./integration-tests.sh:/app/integration-tests.sh:ro
      - ./docs:/app/docs
      - ./setup.py:/app/setup.py
      - ./setup.cfg:/app/setup.cfg
      - ./README.rst:/app/README.rst
      - ./CHANGELOG.rst:/app/CHANGELOG.rst
      - ./MANIFEST.in:/app/MANIFEST.in
    depends_on:
        - "mlflow-test"
    networks:
      - default
      - mlflow
    extra_hosts:
      - rep.msk.mts.ru:10.73.8.86
      - repo.msk.mts.ru:10.73.8.86
  mlflow-test:
    image: docker.rep.msk.mts.ru/bigdata/platform/dsx/mlflow:${MLFLOW_TAG:-latest}
    env_file: .env.test.integration
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    restart: unless-stopped
    depends_on:
        - "mlflow-test-db"
    networks:
      - db
      - mlflow
  mlflow-test-db:
    image: postgres:11.8
    env_file: .env.test.integration
    environment:
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
    restart: unless-stopped
    networks:
      - db
networks:
  mlflow:
    internal: true
  db:
    internal: true
