- name: "mlflow-client-docs deployment"
  hosts: "{{ target_host }}"
  vars_prompt:
    - name: "target_host"
      prompt: "Enter a target host name or a group name where mlflow-client-docs should be installed"
      private: no
    - name: "image_version"
      prompt: "Enter version of mlflow-client-docs to be installed"

  tasks:
    - name: "Start docker service"
      systemd:
        name: docker.service
        enabled: yes
        state: started
      become: true
      become_user: root

    - name: "Install pip packages"
      pip:
        name: ["docker"]

    - name: "Pull docker image"
      docker_image:
        name: "{{ mlflow_client_docs_image }}:{{ image_version }}"
        state: present
        source: pull
        force_source: yes

    - name: "Start nginx"
      docker_container:
        name: "{{ mlflow_client_docs_container }}"
        state: started
        image: "{{ mlflow_client_docs_image }}:{{ image_version }}"
        networks:
          - name: "{{ mlflow_client_docs_network }}"
        network_mode: "{{ mlflow_client_docs_network }}"
        networks_cli_compatible: yes
        init: true
