- name: "documentation deployment"
  hosts: "{{ target_host }}"
  vars_prompt:
    - name: "target_host"
      prompt: "Enter a target host name or a group name where documentation should be installed"
      private: no
    - name: "image_version"
      prompt: "Enter version of documentation to be installed"

  tasks:
    - name: "Start docker service"
      systemd:
        name: docker.service
        enabled: yes
        state: started
      become: true
      become_user: root

    - name: "Install pip packages"
      pip:
        name: ["docker"]

    - name: "Remove docker image"
      docker_image:
        name: "{{ image }}:{{ image_version }}"
        state: absent
        force_absent: true

    - name: "Pull docker image"
      docker_image:
        name: "{{ image }}:{{ image_version }}"
        state: present
        source: pull
        force_source: yes

    - name: "Start nginx"
      docker_container:
        name: "{{ container }}"
        state: started
        image: "{{ image }}:{{ image_version }}"
        networks:
          - name: "{{ network }}"
        network_mode: "{{ network }}"
        networks_cli_compatible: yes
        restart_policy: unless-stopped
        init: true

    - name: Restart nginx proxy
      shell: "docker exec {{ proxy_container }} bash -cl 'nginx -s reload'"
      changed_when: false
